### ISSUE TITLE
Preview window doesn't reflect with the currently open document

### ISSUE THREAD

**Issue by endo64** [stayfool/vscode-asciidoc#1]
When I open an .adoc file and press CTRL+SHIFT-R shortcut key, preview window opens and shows the very first .adoc file I opened before, not the currently active one.

**Comment by stayfool** [comment]
@endo64 use [joaompinto/asciidoctor-vscode](https://github.com/joaompinto/asciidoctor-vscode) instead，this plugin now support render by [Asciidoctor.js](https://asciidoctor.org/docs/asciidoctor.js/)
